### ISSUE TITLE
Firing falling but not rising event..

### ISSUE THREAD

**Issue by richpicking** [akira-cn/rpio2#1]
Hello,
Trying to get this to work to read from a standard ultrasonic sensor (HC-SR04).
I register both rising and falling events on the echo pin (this is supposed to go high for a time duration that represents the time the ultrasonic signal bounces off an object).
The weird thing is that when I listen to the echo pin, I register both rising and falling events... but only the falling one fires.  
If I trigger the sensor in a loop, with the events registered, I still see repeated falling events but never a rising one..  any thoughts on how this is possible ?

Many thanks.

**Comment by akira-cn** [comment]
The poll interval is a 1ms setInterval() and transitions could come in between detecting the event and reading the value. Therefore this interface is only useful for events which transition slower than approximately 1kHz.

The HC-SR04 provides a sharp current less than 1ms(usually 20~50us). That means we'd better use loop to detect the signal change synchronously rather than use interrupt events.
